# Generated by Django 4.0.4 on 2022-07-28 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesAll',
            fields=[
                ('idCategories', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=100)),
                ('idCategories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentariesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='FilesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='filesPDF/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('discount', models.BooleanField()),
                ('oldPrice', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('cloth', models.CharField(max_length=1000, null=True)),
                ('addition', models.CharField(max_length=1000, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
