# Generated by Django 4.0.4 on 2022-08-20 17:05

from django.db import migrations

def create_data(apps, schema_editor):
    BagProducts = apps.get_model('salesUser', 'BagProducts')
    BagProducts(loginUser='legomainia', idProduct='ewfljwjfw;f;', size='34').save()

    SaledProducts = apps.get_model('salesUser', 'SaledProducts')
    SaledProducts(loginUser='legomainia', idProduct='ewfljwjfw;f;', size='34').save()


class Migration(migrations.Migration):

    dependencies = [
        ('salesUser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
