# Generated by Django 4.0.4 on 2022-08-22 11:28

from django.db import migrations

def create_data(apps, schema_editor):
    Courses = apps.get_model('courses', 'Courses')
    Courses(name='reverse', link='https//ewentListener.com', image='').save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
