# Generated by Django 4.0.4 on 2022-06-20 08:33

from django.db import migrations
def create_data(apps, schema_editor):
    Question = apps.get_model('qestionBase', 'Question')
    Question(first_name="test user", wayCalling="telephone", callRealize="+79224843094", questionText="test message").save()


class Migration(migrations.Migration):

    dependencies = [
        ('qestionBase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
